- hosts: gsi-machine
  become: yes
  tasks:
    - name: mise à jour
      apt:
        update_cache: yes

    - name: Installer Apache
      apt:
        name: apache2
        state: present

    - name: Démarrer et activer
      systemd:
        name: apache2
        state: started
        enable: yes

    - name: changer le port
      lineinfile:
        path: /etc/apache2/ports.conf
        regexp: '^Listen 80'
        line: 'Listen 8081'
